   services:
     redis:
       image: redis:7
       container_name: sg-redis
       ports:
         - "6379:6379"

     cassandra:
       image: cassandra:4.1
       container_name: sg-cassandra
       environment:
         MAX_HEAP_SIZE: 512M
         HEAP_NEWSIZE: 128M
       ports:
         - "9042:9042"