apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prom
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provider
data:
  provider.yaml: |
    apiVersion: 1
    providers:
      - name: default
        type: file
        options:
          path: /var/lib/grafana/dashboards
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels: {app: grafana}
  template:
    metadata:
      labels: {app: grafana}
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:11.2.0
          env:
            - {name: GF_AUTH_ANONYMOUS_ENABLED, value: "true"}
            - {name: GF_AUTH_ANONYMOUS_ORG_ROLE, value: Admin}
          ports:
            - containerPort: 3000
          volumeMounts:
            - {name: datasource, mountPath: /etc/grafana/provisioning/datasources}
            - {name: provider, mountPath: /etc/grafana/provisioning/dashboards}
            - {name: dashboard, mountPath: /var/lib/grafana/dashboards}
      volumes:
        - name: datasource
          configMap: {name: grafana-datasource}
        - name: provider
          configMap: {name: grafana-provider}
        - name: dashboard
          configMap: {name: grafana-dashboard}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector: {app: grafana}
  ports:
    - port: 3000